version: '3'

services:

  laravel:
    build:
      context: ./docker/
      dockerfile: laravel.Dockerfile
    restart: always
    env_file:
      - .env
    volumes:
      - .:/usr/share/nginx/html:cached
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
    depends_on:
      - mysql

  http-nginx:
    image: nginx:1.14.2-alpine
    ports:
      - "80:80"
    restart: always
    volumes:
      - ./docker/http-nginx.conf:/etc/nginx/conf.d/default.conf:cached
      - .:/usr/share/nginx/html:cached
    links:
      - laravel
      - mysql
      - redis

  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_DATABASE=phimhdplus
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
    ports:
      - 3306:3306
    volumes:
      - ./mysql:/var/lib/mysql
    command:
      - --innodb-flush-method=O_DSYNC
      - --innodb-use-native-aio=0
      - --character-set-server=utf8
      - --collation-server=utf8_unicode_ci
      - --skip-character-set-client-handshake
      - --sql_mode=STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION

  redis:
    image: redis:alpine
    ports:
      - "6778:6379"
    command: [ "redis-server", "--appendonly", "yes" ]
